let express = require("express")
let bodyParser = require('body-parser')
var cron = require('node-cron');
let app = express();

app.use(bodyParser.urlencoded({ extended: false }))

const accountSid = '';
const authToken = '';
const client = require('twilio')(accountSid, authToken);

const MessagingResponse = require('twilio').twiml.MessagingResponse;

// cron.schedule('50 17 7 October *', () => {
//     console.log(`This will execute on 5:50 , 7 October 2021`);
// });

app.post('/smsResponse', (req, res) => {
    console.log(req.body)
    const twiml = new MessagingResponse();
    twiml.message('Response Message: Hi, I am an autogenerated reply from server');
    res.writeHead(200, { 'Content-Type': 'text/xml' });
    res.end(twiml.toString());
});

app.get("/sendSms", (req, res) => {
    client.messages
        .create({
            body: 'Hello Sir, This is a test message',
            from: '+1',
            messagingServiceSid: '',
            to: '+92'
        })
        .then(message => console.log(message.sid))
        .done();
    res.send({ "response": "Message Sent" })
})

app.listen(3000, () => {
    console.log(`Listining...`)
})
